version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
